name: Rule Provider

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rule providers
        working-directory: ./rule_provider
        run: |
          echo "Downloading rule_games source list..."
          curl -s https://rules.kr328.app/category-games.yaml -o rule_games.yaml
          rm -fr rule_games.yamle


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update Rule Provider Clash
